import { Image } from 'react-native';

export const data = [
    Image.resolveAssetSource(require('../assets/images/Cover.jpg')).uri,
    Image.resolveAssetSource(require('../assets/images/image.2.jpg')).uri,
    Image.resolveAssetSource(require('../assets/images/image.3.jpg')).uri,
    Image.resolveAssetSource(require('../assets/images/image.4.jpg')).uri,
    Image.resolveAssetSource(require('../assets/images/image.5.jpg')).uri,
    Image.resolveAssetSource(require('../assets/images/image.6.jpg')).uri,
    Image.resolveAssetSource(require('../assets/images/image.7.jpg')).uri,
    Image.resolveAssetSource(require('../assets/images/image.8.jpg')).uri,
    Image.resolveAssetSource(require('../assets/images/image.9.jpg')).uri,
    Image.resolveAssetSource(require('../assets/images/image.10.jpg')).uri,
    Image.resolveAssetSource(require('../assets/images/image.11.jpg')).uri,
    Image.resolveAssetSource(require('../assets/images/image.12.jpg')).uri,
    Image.resolveAssetSource(require('../assets/images/image.13.jpg')).uri,
    Image.resolveAssetSource(require('../assets/images/image.14.jpg')).uri,
    Image.resolveAssetSource(require('../assets/images/image.15.jpg')).uri,
    Image.resolveAssetSource(require('../assets/images/image.16.jpg')).uri,
    Image.resolveAssetSource(require('../assets/images/image.17.jpg')).uri,
    Image.resolveAssetSource(require('../assets/images/image.18.jpg')).uri,
    Image.resolveAssetSource(require('../assets/images/image.19.jpg')).uri,
    Image.resolveAssetSource(require('../assets/images/image.20.jpg')).uri,
    Image.resolveAssetSource(require('../assets/images/image.21.jpg')).uri,
    Image.resolveAssetSource(require('../assets/images/image.22.jpg')).uri,
    Image.resolveAssetSource(require('../assets/images/image.23.jpg')).uri,
    Image.resolveAssetSource(require('../assets/images/image.24.jpg')).uri,
];